# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022
    env:
      Solution_Name: AppServiceInProcessSolution.sln        


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
              fetch-depth: 0
 
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Create the app package
        run: msbuild ${{ env.Solution_Name }} /restore /p:Platform=${{ env.Appx_Bundle_Platforms }} /p:AppxBundlePlatforms=${{ env.Appx_Bundle_Platforms }} /p:Configuration=${{ env.Configuration }} /p:UapAppxPackageBuildMode=${{ env.Appx_Package_Build_Mode }} /p:AppxBundle=${{ env.Appx_Bundle }} /p:AppxPackageDir=${{github.workspace}}\AppPackages\ /p:GenerateAppxPackageOnBuild=true
        env:
            Appx_Bundle: Never
            Appx_Bundle_Platforms: x64
            Appx_Package_Build_Mode: SideloadOnly
            Configuration: Release
            
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
             name: MSIX Package
             path: ${{github.workspace}}\AppPackages

